
# CustomJoin by @ItalianDevs4PM (idea by @AryToNeX)

name: CustomJoin
version: "1.1.0"
author: ItalianDevs4PM
authors: ItalianDevs4PM, AryToNeX, fycarman, Flavius12, XEmAX32, NikoZazza, luca28pet
website: http://github.com/ItalianDevs4PM
api: [3.0.0-ALPHA7]
main: CustomJoin\Main
permissions:
  customjoin:
    description: "Main permission"
    default: false
